CREATE TABLE Cuisine (
    cuisine_id      NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 11 INCREMENT BY 1) PRIMARY KEY,
    cuisine_name    VARCHAR2(100) NOT NULL
);
 
begin
INSERT INTO Cuisine (cuisine_name) VALUES ('Italian');
INSERT INTO Cuisine (cuisine_name) VALUES ('Indian');
INSERT INTO Cuisine (cuisine_name) VALUES ('Asian');
INSERT INTO Cuisine (cuisine_name) VALUES ('Mexican');
INSERT INTO Cuisine (cuisine_name) VALUES ('Greek'); 
INSERT INTO Cuisine (cuisine_name) VALUES ('American');
end; 

select * from Cuisine;

CREATE TABLE User_Details (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    user_name VARCHAR2(50) NOT NULL,
    password VARCHAR2(100) NOT NULL,  -- Store hashed passwords
    email VARCHAR2(100),
    is_admin NUMBER(1) DEFAULT 0,  -- 0 for regular users, 1 for admins
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO User_Details (user_name, password, email, is_admin)
VALUES ('Nanditha_potam', 'Password@123', 'abcd@gmail.com', 1);

select * from User_details;

CREATE TABLE Recipe (
    recipe_id           NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    recipe_name         VARCHAR2(100) NOT NULL,
    cuisine_id          NUMBER,
    cooking_time_min    NUMBER,
    ingredients         clob, 
    calories            DECIMAL,
    instruction         CLOB,
    dietary_restriction VARCHAR2(250),
    servings            NUMBER,
    user_id             NUMBER,  -- Links to the user who created the recipe
    FOREIGN KEY (cuisine_id) REFERENCES Cuisine(cuisine_id),
    FOREIGN KEY (user_id) REFERENCES User_Details(user_id)  -- Link to user details
);

BEGIN 
    -- 1. Pizza 
    INSERT INTO Recipe (recipe_name, cuisine_id, cooking_time_min, ingredients, calories, instruction, dietary_restriction, servings, user_id) 
    VALUES ('Pizza', 11, 120, 'Dough, flour, yeast, water, salt, tomato sauce, mozzarella cheese, pepperoni, basil.', 500, 
            '1. Mix flour, yeast, water, and salt for dough. Let rise. Roll out, top with tomato sauce, mozzarella, pepperoni, and basil. Bake at 475°F for 10-15 minutes. Enjoy your homemade pizza, crispy crust, gooey cheese, and flavorful toppings!', 
            'gluten free', 4, 1); 

    -- 2. Butter Chicken 
    INSERT INTO Recipe (recipe_name, cuisine_id, cooking_time_min, ingredients, calories, instruction, dietary_restriction, servings, user_id) 
    VALUES ('Butter Chicken', 12, 50, 'Chicken, yogurt, butter, cream, tomatoes, onions, garlic, ginger, garam masala, coriander, cumin, kasuri methi', 800, 
            'Marinate chicken in yogurt, spices, and lemon juice. Sauté onion, garlic, and ginger. Add marinated chicken, tomato puree, and cream. Simmer until chicken is cooked. Garnish with butter and cilantro. Serve with rice or naan. Enjoy creamy, flavorful butter chicken!', 
            'gluten free', 4, 1); 

    -- 3. Ramen 
    INSERT INTO Recipe (recipe_name, cuisine_id, cooking_time_min, ingredients, calories, instruction, dietary_restriction, servings, user_id) 
    VALUES ('Ramen', 13, 30, 'Noodles, veggie broth, boiled eggs, green onions, mushrooms, garlic, ginger', 400, 
            'Boil ramen noodles in water. In a separate pot, simmer broth with ginger, garlic, soy sauce, and mirin. Add cooked noodles, veggies. Serve hot.', 
            'soy free', 3, 1); 

    -- 4. Tacos 
    INSERT INTO Recipe (recipe_name, cuisine_id, cooking_time_min, ingredients, calories, instruction, dietary_restriction, servings, user_id) 
    VALUES ('Tacos', 14, 60, 'Cucumber, taco shells, lettuce, tomatoes, vegan cheese, salsa, avocado, lime', 200, 
            'Season and cook veggies with taco seasoning. Warm tortillas. Fill with cucumber, lettuce, tomato, cheese, and salsa. Optionally, add sour cream. Enjoy your delicious homemade tacos!', 
            'vegan', 6, 1); 

    -- 5. Greek Salad 
    INSERT INTO Recipe (recipe_name, cuisine_id, cooking_time_min, ingredients, calories, instruction, dietary_restriction, servings, user_id) 
    VALUES ('Greek Salad', 15, 15, 'Cucumbers, tomatoes, red onions, bell peppers, kalamata olives, feta cheese, olive oil, red wine vinegar, dried oregano, salt, pepper', 100, 
            'Combine chopped cucumbers, tomatoes, onions, and bell peppers in a large bowl. Add kalamata olives and crumbled feta cheese to the bowl. Drizzle olive oil and red wine vinegar over the salad. Sprinkle with dried oregano, salt, and pepper to taste. Toss gently to combine. Serve immediately or refrigerate until ready to serve.', 
            'keto', 1, 1); 

    -- 6. Pasta 
    INSERT INTO Recipe (recipe_name, cuisine_id, cooking_time_min, ingredients, calories, instruction, dietary_restriction, servings, user_id) 
    VALUES ('Pasta', 11, 30, 'Pasta, bell peppers, cherry tomatoes, broccoli, carrots, garlic, olive oil, vegan cheese, basil leaves, salt, pepper', 400, 
            'Cook pasta according to package instructions. Meanwhile, sauté garlic in olive oil until fragrant. Add assorted vegetables and cook until tender-crisp. Toss cooked pasta with vegetables, Parmesan cheese, basil leaves, salt, and pepper. Serve hot, optionally garnished with more Parmesan and fresh herbs.', 
            'Vegan', 2, 1); 

    -- 7. Brownie 
    INSERT INTO Recipe (recipe_name, cuisine_id, cooking_time_min, ingredients, calories, instruction, dietary_restriction, servings, user_id) 
    VALUES ('Brownie', 16, 40, 'Cocoa powder, butter, sugar, eggs, flour, chocolate chips.', 150, 
            'Mix melted butter, sugar, eggs, cocoa, flour, and vanilla. Bake at 350°F for 20-25 minutes. Enjoy the rich, chocolatey goodness of homemade brownies!', 
            'sugars', 1, 1); 

    -- 8. Roti 
    INSERT INTO Recipe (recipe_name, cuisine_id, cooking_time_min, ingredients, calories, instruction, dietary_restriction, servings, user_id) 
    VALUES ('Roti', 12, 20, 'Whole wheat flour, water, salt, ghee, oil', 200, 
            'Knead whole wheat flour, water, and salt into a dough. Divide into balls, flatten into discs. Cook on a hot griddle until bubbles form. Optionally brush with ghee or oil before serving.', 
            'Vegan', 1, 1); 

    -- 9. Burger 
    INSERT INTO Recipe (recipe_name, cuisine_id, cooking_time_min, ingredients, calories, instruction, dietary_restriction, servings, user_id) 
    VALUES ('Burger', 16, 30, 'Chicken, salt, pepper, burger buns, lettuce, tomato, onion, cheese, and condiments like ketchup and mustard.', 600, 
            'Season the chicken, shape into patties, grill to desired doneness. Toast buns, assemble with lettuce, tomato, onion, cheese, and condiments. Serve hot and juicy for a delicious homemade burger.', 
            'nut free', 1, 1); 

    -- 10. Hyderabadi Biryani 
    INSERT INTO Recipe (recipe_name, cuisine_id, cooking_time_min, ingredients, calories, instruction, dietary_restriction, servings, user_id) 
    VALUES ('Hyderabadi Biryani', 12, 60, 'Basmati rice, chicken, onions, tomatoes, yogurt, ginger-garlic paste, green chilies, cinnamon, cardamom, cloves, saffron, mint leaves, coriander leaves, ghee, oil', 700, 
            'Marinate meat in yogurt, spices, and ginger-garlic paste. Cook rice until partially done. Layer rice and meat in a pot, alternating with fried onions, saffron-infused milk, mint, and cilantro. Cook covered until meat is tender and rice is fully cooked.', 
            'gluten free', 3, 1); 
END;


CREATE TABLE rate_review (
    review_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          NUMBER,
    recipe_id        NUMBER,
    rating           NUMBER,
    review           VARCHAR2(100),
    review_date      DATE DEFAULT CURRENT_DATE,
    FOREIGN KEY (user_id) REFERENCES user_details(user_id),
    FOREIGN KEY (recipe_id) REFERENCES recipe(recipe_id),
    CONSTRAINT chk_rating_range CHECK (rating BETWEEN 1 AND 5)
);


CREATE TABLE tag_type (
    tag_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag_name VARCHAR2(50) NOT NULL
);

BEGIN
    INSERT INTO tag_type (tag_name) VALUES ('veg');
    INSERT INTO tag_type (tag_name) VALUES ('non-veg');
    INSERT INTO tag_type (tag_name) VALUES ('contains egg');
    INSERT INTO tag_type (tag_name) VALUES ('breakfast');
    INSERT INTO tag_type (tag_name) VALUES ('lunch');
    INSERT INTO tag_type (tag_name) VALUES ('snacks');
    INSERT INTO tag_type (tag_name) VALUES ('dinner');
END;

select * from tag_type;

CREATE TABLE recipe_tag (
    recipe_id NUMBER,
    tag_id NUMBER,
    FOREIGN KEY (recipe_id) REFERENCES recipe(recipe_id),
    FOREIGN KEY (tag_id) REFERENCES tag_type(tag_id),
    PRIMARY KEY (recipe_id, tag_id)  -- Composite primary key
);


BEGIN
    -- Recipe 1: Pizza
    INSERT INTO recipe_tag (recipe_id, tag_id) VALUES (1, 2);  -- non-veg
    INSERT INTO recipe_tag (recipe_id, tag_id) VALUES (1, 6);  -- dinner

    -- Recipe 2: Butter Chicken
    INSERT INTO recipe_tag (recipe_id, tag_id) VALUES (2, 2);  -- non-veg
    INSERT INTO recipe_tag (recipe_id, tag_id) VALUES (2, 6);  -- dinner

    -- Recipe 3: Ramen
    INSERT INTO recipe_tag (recipe_id, tag_id) VALUES (3, 1);  -- veg
    INSERT INTO recipe_tag (recipe_id, tag_id) VALUES (3, 4);  -- lunch

    -- Recipe 4: Tacos
    INSERT INTO recipe_tag (recipe_id, tag_id) VALUES (4, 1);  -- veg
    INSERT INTO recipe_tag (recipe_id, tag_id) VALUES (4, 5);  -- snacks

    -- Recipe 5: Greek Salad
    INSERT INTO recipe_tag (recipe_id, tag_id) VALUES (5, 1);  -- veg
    INSERT INTO recipe_tag (recipe_id, tag_id) VALUES (5, 4);  -- lunch

    -- Recipe 6: Pasta
    INSERT INTO recipe_tag (recipe_id, tag_id) VALUES (6, 1);  -- veg
    INSERT INTO recipe_tag (recipe_id, tag_id) VALUES (6, 4);  -- lunch

    -- Recipe 7: Brownie
    INSERT INTO recipe_tag (recipe_id, tag_id) VALUES (7, 1);  -- veg
    INSERT INTO recipe_tag (recipe_id, tag_id) VALUES (7, 5);  -- snacks

    -- Recipe 8: Roti
    INSERT INTO recipe_tag (recipe_id, tag_id) VALUES (8, 1);  -- veg
    INSERT INTO recipe_tag (recipe_id, tag_id) VALUES (8, 6);  -- dinner

    -- Recipe 9: Burger
    INSERT INTO recipe_tag (recipe_id, tag_id) VALUES (9, 2);  -- non-veg
    INSERT INTO recipe_tag (recipe_id, tag_id) VALUES (9, 6);  -- dinner

    -- Recipe 10: Hyderabadi Biryani
    INSERT INTO recipe_tag (recipe_id, tag_id) VALUES (10, 2); -- non-veg
    INSERT INTO recipe_tag (recipe_id, tag_id) VALUES (10, 4); -- lunch
    INSERT INTO recipe_tag (recipe_id, tag_id) VALUES (10, 6); -- dinner
END;

CREATE TABLE nutrition_info( 
    recipe_id   NUMBER PRIMARY KEY, 
    carbs       NUMBER, 
    protein     NUMBER, 
    fat         NUMBER, 
    CONSTRAINT recipe_id_fk FOREIGN KEY (recipe_id) REFERENCES recipe(recipe_id) 
);

BEGIN 
    INSERT INTO nutrition_info VALUES (1, 25, 12, 12);  -- Pizza
    INSERT INTO nutrition_info VALUES (2, 15, 25, 20);  -- Butter Chicken
    INSERT INTO nutrition_info VALUES (3, 35, 10, 15);  -- Ramen
    INSERT INTO nutrition_info VALUES (4, 20, 10, 10);  -- Tacos
    INSERT INTO nutrition_info VALUES (5, 12, 4, 9);    -- Greek Salad
    INSERT INTO nutrition_info VALUES (6, 35, 7, 2);    -- Pasta
    INSERT INTO nutrition_info VALUES (7, 25, 3, 12);   -- Brownie
    INSERT INTO nutrition_info VALUES (8, 18, 3, 2);    -- Roti
    INSERT INTO nutrition_info VALUES (9, 23, 18, 12);   -- Burger
    INSERT INTO nutrition_info VALUES (10, 40, 15, 15);  -- Hyderabadi Biryani
END; 

CREATE TABLE TIPS( 
    recipe_id NUMBER, 
    cooking_tip VARCHAR2(500), 
    tutorial_video VARCHAR2(500), 
    CONSTRAINT fk_recipe_id FOREIGN KEY (recipe_id) REFERENCES recipe(recipe_id)
);

BEGIN 
INSERT INTO TIPS VALUES(1, 'Preheat oven for at least 30 minutes before baking.', 'https://youtu.be/sv3TXMSv6Lw?si=R6JNMfUtmrfTo6tJ'); 
INSERT INTO TIPS VALUES(2, 'Marinate chicken for at least 1 hour for best flavor.', 'https://youtu.be/a03U45jFxOI?si=M5ZltfxBFFFZsB9E'); 
INSERT INTO TIPS VALUES(3, 'Add a splash of soy sauce for extra umami flavor.', 'https://youtu.be/B8y3SSmz4sg?si=sN3jLRNH0jkGIraa'); 
INSERT INTO TIPS VALUES(4, 'For extra flavor, season and cook your veggies separately with taco seasoning before assembling your tacos.', 'https://youtu.be/Os7CAOoEvvc?si=t1WTxeUkmYevGZuq'); 
INSERT INTO TIPS VALUES(5, 'For an authentic touch crumble feta cheese over your Greek salad just before serving to preserve its freshness and flavor.', 'https://youtu.be/dDhOpHcAJGo?si=flsvmZn6M3mFgvbj'); 
INSERT INTO TIPS VALUES(6, 'To ensure a moist and fudgy texture, slightly underbake your brownies and allow them to cool completely in the pan before slicing.', 'https://youtu.be/8bi1MaUuzcQ?si=5y-pu0J4dfylhESp'); 
INSERT INTO TIPS VALUES(7, 'For juicier burgers, avoid pressing down on them with a spatula while they are cooking to retain their natural juices and flavor.', 'https://youtu.be/L6yX6Oxy_J8?si=UGFE2BoXqoh5WIUj'); 
INSERT INTO TIPS VALUES(8, 'To keep roti soft and pliable, cover them with a clean kitchen towel immediately after cooking to prevent them from drying out.', 'https://youtu.be/1vQ34bs_dTw?si=8z56kEed3u9Lq0VX'); 
INSERT INTO TIPS VALUES(9, 'For rich flavor, marinate the meat with yogurt, spices, and ginger-garlic paste overnight before cooking the Hyderabadi Biryani.', 'https://youtu.be/mFZkmjC2B3Y?si=zCEINDCZB9f3Itkp'); 
INSERT INTO TIPS VALUES(10, 'To prevent pasta from sticking together, stir it occasionally while cooking and rinse it briefly with cold water after draining.', 'https://youtu.be/bcnPfcJnYr0?si=ObTC2SvXaDcClXGz'); 
END;  

CREATE TABLE avg_rating( 
    recipe_id NUMBER primary key, 
    avg_rating NUMBER DEFAULT 0,
    FOREIGN KEY (recipe_id) REFERENCES Recipe(recipe_id)
); 

begin
INSERT INTO avg_rating (recipe_id, avg_rating) VALUES (1,0);
INSERT INTO avg_rating (recipe_id, avg_rating) VALUES (2,0);
INSERT INTO avg_rating (recipe_id, avg_rating) VALUES (3,0);
INSERT INTO avg_rating (recipe_id, avg_rating) VALUES (4,0);
INSERT INTO avg_rating (recipe_id, avg_rating) VALUES (5,0);
INSERT INTO avg_rating (recipe_id, avg_rating) VALUES (6,0);
INSERT INTO avg_rating (recipe_id, avg_rating) VALUES (7,0);
INSERT INTO avg_rating (recipe_id, avg_rating) VALUES (8,0);
INSERT INTO avg_rating (recipe_id, avg_rating) VALUES (9,0);
INSERT INTO avg_rating (recipe_id, avg_rating) VALUES (10,0);
end;
